language: python
python:
  - "3.4"
services:
  - mongodb
install:
  - "pip install -e .[test]"
before_script:
  - mongorestore tests/db
script:
  - coverage run --source stamps -m py.test -rs
after_success:
  - codecov
  - coverage report -m
